### ISSUE TITLE
Message 수정

### ISSUE THREAD

**Issue by jinyoung** [TheOpenCloudEngine/uEngine-bill#22]
1. Terminology 통합
1.1. Usages --> Usage-based
1.1. Fixed --> One-time
1.1. Edit Customer --> Account 

1. 사용성
1.1. Tiered pricing 에서, max 이상은 최종값으로 처리됩니다. 라고 표시
1.1. Plan 등록시 오류가 서버에서 클라이언트로 표시 필요 --> 간단히라도.

1. 동적 카탈로그 방식으로 저장? 
1.1 그렇다면, 버전관리는 자체적으로 해주나?
1.1 버전관리가 안된다면 이전 가입자의 가입 기간에 대한 그사이 변경된 단가 비용 정산은 어떻게 하는가?

1. 연동관련 
1.1. IAM의 인증토큰과 연결되어 account 처리되는가?
1.1. 미터링에서 통합하여 사용량을 어떻게 보내주어야 하는가?

1. 브랜드 통합 관련
1.1. 통합 스타일링
1.1. 통합 로고 혹은 각자 로고

**Comment by SeungpilPark** [comment]
Terminology 통합
1.1. Usages --> Usage-based
1.1. Fixed --> One-time
1.1. Edit Customer --> Account

사용성
1.1. Tiered pricing 에서, max 이상은 최종값으로 처리됩니다. 라고 표시
1.1. Plan 등록시 오류가 서버에서 클라이언트로 표시 필요 --> 간단히라도.

동적 카탈로그 방식으로 저장?
1.1 그렇다면, 버전관리는 자체적으로 해주나?
1.1 버전관리가 안된다면 이전 가입자의 가입 기간에 대한 그사이 변경된 단가 비용 정산은 어떻게 하는가?

==> 
 - Catalog: 단일 effective date 를 가지고 있는 카달로그 한장.
 - Versioned Catalog: 각기 다른 effective date 를 가지고 있는 Catalog 여러장 묶음

킬빌 내에 삽입된 유엔진 플러그인은,  이전 가입자의 가입기간에 대한 그사이 변경된 단가(이전 버젼) 및 현재 단가(현재 버젼)를 Versioned Catalog 로 구성함.
         

연동관련
1.1. IAM의 인증토큰과 연결되어 account 처리되는가?
1.1. 미터링에서 통합하여 사용량을 어떻게 보내주어야 하는가?

==>
 - account 는 IAM 인증과 관련이 없고, 빌링 서비스를 로그인 하는 서비스 운영자에 한함.
 - 미터링에서 통합하여 사용량을 보내주는 것은 엑셈에서 RabbitMQ(API 카운트 수집) + 빌링 미터링 계산 모듈이 준비중

브랜드 통합 관련
1.1. 통합 스타일링
1.1. 통합 로고 혹은 각자 로고
